id: QmP1QDzuaYtqNVFy6qXKsysSXqu5ZdYsBvDG4v27QyGdvE
description: ""
tags: []
source: libraries/snake_001
trigger:
    type: https
    method: POST
    paths:
        - /001/end
domains:
    - dom
execution:
    timeout: 10s
    memory: 10MB
    call: end
