id: QmPyLe1bbqaMQNcroVpuHCmq5w59HKLZw9DyPbjxV9vrx2
description: ""
tags: []
source: libraries/snake_001
trigger:
    type: https
    method: POST
    paths:
        - /001/move
domains:
    - dom
execution:
    timeout: 60s
    memory: 10MB
    call: move
