id: Qmd5feuj2QUDD9CJpS4o6WjKo8kH2agdSW2w3K4eBftxQ1
description: ""
tags: []
source: .
trigger:
    type: https
    method: GET
    paths:
        - /ping
domains:
    - dom
execution:
    timeout: 10s
    memory: 10MB
    call: ping
